description: >
  This is the executor for deployments with deployer.

parameters:
  image:
    type: string
    default: ubuntu-2004:202010-01
    description: >
      Pick a specific circleci image variant:
      https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
  working_directory:
    type: string
    default: ~/src
    description: >
      Default working directory.

machine:
  image: << parameters.image >>

working_directory: << parameters.working_directory >>
