description: >
  This is the executor for deployments with deployer.

parameters:
  image:
    type: string
    default: ubuntu-2004:202010-01
    description: >
      Pick a specific circleci image variant:
      https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
  env:
    type: enum
    default: "test"
    enum: [ "dev", "test", "prod" ]

machine:
  image: << parameters.image >>

working_directory: ~/src
